// Filenames (without extension) of the SVGs in src/assets/icons/.
export type IconName =
  | 'arrow-up'
  | 'badge'
  | 'behance'
  | 'briefcase'
  | 'camrecorder'
  | 'chevron-left'
  | 'chevron-right'
  | 'close'
  | 'cup'
  | 'dribbble'
  | 'fire'
  | 'graduation'
  | 'instagram'
  | 'link'
  | 'magnifier-add'
  | 'music-tone-alt'
  | 'options'
  | 'people'
  | 'picture'
  | 'pinterest-p'
  | 'spinner'
  | 'twitter'
